### ISSUE TITLE
Include data classification in schema

### ISSUE THREAD

**Issue by gdestuynder** [mozilla-iam/cis_hris_publisher#1]
In https://github.com/andrewkrug/cis_hris_publisher/blob/master/hris_publisher/schema.json

We should add one attribute such as:

```
"properties": {
    "Cost_Center": {
      "id": "/properties/Cost_Center",
      "type": "string".
       "classification": "STAFF CONFIDENTIAL"
},
```

As per https://wiki.mozilla.org/Security/Data_Classification

This will allow us to be flexible about what/how information/data is shared in the future and apply classification easily, be it coming from hris or anything else.

cc @floatingatoll for information

**Comment by andrewkrug** [comment]
@gdestuynder we will do this before this goes live.  I'll slate it for the next sprint.
