### ISSUE TITLE
Differenciate staff vs contractor

### ISSUE THREAD

**Issue by gdestuynder** [mozilla-iam/cis_hris_publisher#12]
Currently if workday field `WorkerType` is set we consider the profile to be staff (`hris_is_staff`) however, some would like to differentiate types of staff, in particular contractor.

We could do `hris_is_contractor` or `hris_worktype_xxx`

See also https://github.com/mozilla/doorman/issues/97

**Comment by andrewkrug** [comment]
This is done!
